#include <GL/glut.h>

const GLfloat GROUND_WIDTH = 30.0f;
const GLfloat GROUND_LENGTH = 50.0f;
const GLfloat GROUND_HEIGHT = 0.25f;

const GLfloat FIELD_WIDTH = GROUND_WIDTH - 5.0f;
const GLfloat FIELD_LENGTH = GROUND_LENGTH - 5.0f;

const GLdouble FIELD_WIDTH_START = -(GROUND_WIDTH / 2);
const GLdouble FIELD_WIDTH_END = -FIELD_WIDTH_START;
const GLdouble FIELD_LENGTH_START = -(GROUND_LENGTH / 2);
const GLdouble FIELD_LENGTH_END = -FIELD_LENGTH_START;

const GLfloat CROSSBAR_LENGTH = 5.0f;
const GLfloat CROSSBAR_HEIGHT = 2.2f;

const GLfloat CROSSBAR_LEFT_NET_WIDTH_START = -(GROUND_LENGTH / 2);
const GLfloat CROSSBAR_LEFT_NET_WIDTH_END = -(FIELD_LENGTH / 2) - 0.5;
const GLfloat CROSSBAR_LEFT_NET_LENGTH_START = -(CROSSBAR_LENGTH / 2);
const GLfloat CROSSBAR_LEFT_NET_LENGTH_END = -(CROSSBAR_LEFT_NET_LENGTH_START);

const GLfloat CROSSBAR_RIGHT_NET_WIDTH_START = -CROSSBAR_LEFT_NET_WIDTH_END;
const GLfloat CROSSBAR_RIGHT_NET_WIDTH_END = -CROSSBAR_LEFT_NET_WIDTH_START;
const GLfloat CROSSBAR_RIGHT_NET_LENGTH_START = CROSSBAR_LEFT_NET_LENGTH_START;
const GLfloat CROSSBAR_RIGHT_NET_LENGTH_END = CROSSBAR_LEFT_NET_LENGTH_END;

const GLdouble BALL_RADIUS = 0.25;
